"""make transactions provider nullable

Revision ID: 9333baec37df
Revises: 301117dd9e40
Create Date: 2026-07-23 13:41:30.756588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9333baec37df'
down_revision: Union[str, Sequence[str], None] = '301117dd9e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'provider',
               existing_type=postgresql.ENUM('google', 'microsoft', name='provider_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'provider',
               existing_type=postgresql.ENUM('google', 'microsoft', name='provider_enum'),
               nullable=False)
    # ### end Alembic commands ###
